name: Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - uses: actions/setup-node@v6
        with:
          node-version: 24.5

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec moon run docs:build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: apps/docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
